language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - "pip install -r requirements-dev.txt"
  - "python setup.py install"
before_script:
  - "flake8 sodapy/"
  - "flake8 tests/"
script: pytest
